version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: daily
    ignore:
      - dependency-name: "org.slf4j:*"
      - dependency-name: "org.apache.logging.log4j:*"
